# Generated by Django 5.1.5 on 2025-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField(default='NULL', max_length=500)),
                ('diagnosis', models.CharField(max_length=255)),
                ('speciall_disease', models.CharField(choices=[('yes', 'YES'), ('No', 'NO')], default='NO', max_length=3)),
                ('Medical_Problems', models.TextField(default='NULL', max_length=700)),
            ],
        ),
    ]
